# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24fb4e543c09d59e04f4d7c87d97fb32d159b69b1271ec02baac2ed8ed92fa9f900137f2877e4e702c3ee0857433ebf8b1a869b5c01af75f904f009fbe8a4996

test:
  secret_key_base: d40c5dde22b8bd3e1de71b8c01d141ef0b295d221a16c3d71d9a90dba28b79119bbe715a5456548613fd296b5994635eeb001dc89033eb73a55e938a31ae9070

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
